packages:
  - packages/*

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest

catalogs:
  dev:
    "@antdv-next/auto-import-resolver": ^1.0.5
    "@tsconfig/node24": ^24.0.4
    "@vitejs/plugin-vue": ^6.0.4
    "@vitejs/plugin-vue-jsx": ^5.1.4
    "@vue/language-core": ^3.2.5
    "@vue/test-utils": ^2.4.6
    "@vue/tsconfig": ^0.9.0
    jiti: ^2.6.1
    jsdom: ^28.1.0
    npm-run-all2: ^8.0.4
    postcss-selector-parser: ^7.1.0
    tinyglobby: ^0.2.15
    typescript: ~5.9.3
    unplugin-auto-import: ^21.0.0
    unplugin-dts: 1.0.0-beta.6
    unplugin-vue-components: ^31.0.0
    vite: beta
    vite-plugin-dayjs: ^1.0.1
    vite-plugin-inspect: ^11.3.3
    vite-plugin-tsx-resolve-types: ^1.0.1
    vite-plugin-vue-devtools: ^8.0.7
    vite-plugin-vue-resolve-types: ^0.0.1
    vitest: ^4.0.18
    vue-tsc: ^3.2.5
  docs:
    "@antdv-next/unocss": ^1.0.2
    "@mdit-vue/plugin-frontmatter": ^2.1.4
    "@mdit-vue/plugin-headers": ^2.1.4
    "@mdit-vue/plugin-title": ^2.1.4
    "@mdit-vue/plugin-toc": ^2.1.4
    "@mdit-vue/shared": ^2.1.4
    "@mdit-vue/types": ^2.1.4
    "@shikijs/markdown-it": ^3.13.0
    "@shikijs/transformers": ^3.13.0
    markdown-it: ^14.1.0
    markdown-it-anchor: ^9.2.0
    markdown-it-async: ^2.2.0
    markdown-it-attrs: ^4.3.1
    markdown-it-container: ^4.0.0
    markdown-it-emoji: ^3.0.0
    shiki: ^3.13.0
    unocss: ^66.6.6
  prod:
    "@ant-design/fast-color": ^3.0.1
    "@antdv-next/cssinjs": ^1.0.4
    "@antdv-next/icons": ^1.0.4
    "@vueuse/core": ^14.2.1
    antdv-next: ^1.1.2
    dayjs: ^1.11.19
    lru-cache: ^11.2.2
    mlly: ^1.8.0
    nanoid: ^5.1.6
    pathe: ^2.0.3
    picomatch: ^4.0.3
    pinia: ^3.0.4
    vue: ^3.5.29
    vue-i18n: ^11.2.8
    vue-router: ^5.0.3
  types:
    "@types/jsdom": ^28.0.0
    "@types/markdown-it": ^14.1.2
    "@types/node": ^24.12.0
    "@types/picomatch": ^4.0.2

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - esbuild

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"

shellEmulator: true
